//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 01:51:51 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://a9.com/-/spec/opensearch/1.1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gr.cite.opensearch.schema;
