/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yannis' at '2/12/16 6:33 PM' with Gradle 2.9
 *
 * @author yannis, @date 2/12/16 6:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
